# подкаталоги, в которых линтер не будет делать проверку кода
excluded:
  - Carthage
  - Pods
  - LingvaVestra/SwiftGen

disabled_rules:
  - trailing_whitespace

# максимально допустимая длина строки
line_length:
  warning: 120
  ignores_function_declarations: true

# настройка содержимого типа
type_body_length:
  warning: 400
  error: 600

# настройка содержимого файла
file_length:
  warning: 500
  error: 1200
  ignore_comment_only_lines: true

# настройка названия типа
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names

# настройка названия переменной
identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - x
    - y
    - z
    - id

# настройка уровня вложения
nesting:
  type_level: 4

# максимально допустимое кол-во предупреждений
warning_threshold: 20
